### PR TITLE
cleaned up redirects removed from 18f/dns

### PR DESCRIPTION
**Pull request by robert-bryson**
Related to https://github.com/GSA/data.gov/issues/4233

Cleans up redirects that were removed from 18f/dns. 

Please confirm @FuhuXia  that these look correct.

### CODE REVIEW

**Comment by FuhuXia** [comment]
The purpose of this PR is to synchronize removal of domains that have been removed from DNS. I see agriculture and energy are still valid DNS entries, so we should keep them here.

**Comment by robert-bryson** [comment]
@FuhuXia , I see those routes resulting in 
image

and 

image.

Are you saying that keeping these 404s is correct and what you want me to do?

**Comment by FuhuXia** [comment]
Yes, we can keep them for now, and delete them when they are removed from the DNS.

**Comment by FuhuXia** [comment]
Since you have gone thru the Touchpoints, and `agriculture` and `energy` are not on the removal list, there is no need to remove them from DNS. So no need for any new DNS PRs. If `agriculture` and `energy` stay in the DNS, we should have them in the redirect.

**Comment by FuhuXia** [comment]
Ok, in that case, they should be removed from 18f/DNS and this redirect then.

**Comment by robert-bryson** [comment]
> Ok, in that case, they should be removed from 18f/DNS and this redirect then.

Great! Removed here and will be removed there once the [lords of 18f shine their faces upon us.](https://github.com/18F/dns/pull/640)

**Review by FuhuXia — APPROVED** [review]

**Comment by robert-bryson** [comment]
I don't think that pages/build check is going to return a status. I haven't been working in this repo recently, are we expecting it to? If not, can we override?

**Pull request merged**
